#!/bin/bash

# reload wallpaper so that it scales properly on new display
feh-nasa

# disable touchpad gestures on multi-monitor setup
# (will usually have an external mouse).
if [ "$(xrandr --query | grep " connected" | wc -l)" == "1" ]; then
  libinput-gestures-setup start
else
  libinput-gestures-setup stop
fi
